### ISSUE TITLE
New version crashes with Waves Plugins

### ISSUE THREAD

**Issue by BasicPro** [teragonaudio/MrsWatson#197]
Hi!

Great work with the new version upgrades, I've read buffer compensation is solved and you've added support for multiple bit depth and formats, thanks a lot!

However with this new version I get this error with Waves Shell Plugins.

ERROR: Sent signal 11, exiting
MrsWatson (or one of its hosted plugins) has encountered a serious error and
crashed.

I don't have this error with the previous version :(

Let me know if you need more info or if you have any idea of what it might be causing this problem

Regards

**Comment by BasicPro** [comment]
If I separate the plugins with shell2vst it works although I get this error, that repeats each certain number of frames:

INTERNAL ERROR: framesProcessed <12005952> != getAudioClock<>-->currentFrame <1200588>
This should not have happened. Please take a minute to report a bug

I get the error with all the plugins I've tried so far. I guess the frames processed and the current frame is not the same, the file ends being a bit longer than the original one.

Regards

**Comment by nikreiman** [comment]
Hmm, sounds like a regression, I'll check the crash out right away.
Regarding the warning message, I have noticed that as well. Should be an
easy fix.

**Comment by BasicPro** [comment]
Thanks for checking, let me know any news :)

**Comment by barba3** [comment]
Hello, any news? I'm stuck on this too

**Comment by nikreiman** [comment]
Haven't had time to do any MrsWatson hacking recently, sorry for the delay. I'll probably have enough time to sit down over Easter and solve a bunch of MW bugs.

**Comment by Joerg69** [comment]
This is the same Error message I get with my TC powercore (reported yesterday) ... would be great if you will find the time to fix it!!! Happy Easter!

**Comment by nikreiman** [comment]
I think that I have fixed the issue, if you would like to try out a build here is a 32-bit Mac binary which contains the fix:

https://dl.dropboxusercontent.com/u/5747435/mrswatson

**Comment by JoergKn** [comment]
Dear Nik!

 

Thanks for the link! I would love to test the new build, but I’m using MrsWatson on a windows 7 – 64-bit system! Can you please compile a suitable version so I will start testing immediately!

 

Thanks again - best regards!

 

Joerg

 

 

Von: Nik Reiman [mailto:notifications@github.com] 
Gesendet: Samstag, 4. April 2015 15:22
An: teragonaudio/MrsWatson
Cc: JoergKn
Betreff: Re: [MrsWatson] New version crashes with Waves Plugins (#197)

 

I think that I have fixed the issue, if you would like to try out a build here is a 32-bit Mac binary which contains the fix:

https://dl.dropboxusercontent.com/u/5747435/mrswatson

—
Reply to this email directly or view it on GitHub <https://github.com/teragonaudio/MrsWatson/issues/197#issuecomment-89576972> .  <https://github.com/notifications/beacon/ALKEU-dut2JiLgN4YcaCn9V1pK_7p9rsks5n790SgaJpZM4Dc44F.gif> 

  _____  

E-Mail ist virenfrei.
Von AVG überprüft - www.avg.de
Version: 2015.0.5863 / Virendatenbank: 4321/9451 - Ausgabedatum: 04.04.2015

**Comment by nikreiman** [comment]
Windows build (32-bit) is here:

https://dl.dropboxusercontent.com/u/5747435/mrswatson.exe

**Comment by JoergKn** [comment]
Dear Nik!

Thanks - but I would need 64-bit Windows! Can you please provide a 64-bit build so I can start testing!?

Thanks!

Joerg

Von meinem iPhone gesendet

**Comment by JoergKn** [comment]
Hmmm - the 32-bit version from the link above still show version 0.9.8 - build 20150122!?
But it has to be a new build as it didn't show any "internal errors" anymore - YEAH! But now it shows all frames that are processed like in a verbose mode!? When choosing PCM as output there are no such messages! Would be good if they are switched off in WAV output as well!

For the delay compensation, it is still the same! The frames are still not in the same position as before processing - I will report this in the corresponding bugreport!

**Comment by BasicPro** [comment]
Thanks a lot for the Windows Build, really appreciated, I will be testing this in my server next week, I'll let you know if everything works correctly!

Regards

**Comment by JoergKn** [comment]
@nikreiman: Here is a picture from your yesterday build - no more "internal Error!" messages - Good stuff! But when selecting WAV output MW shows all processed frames similar to the verbose verbose mode!

![mrswatson_verbose](https://cloud.githubusercontent.com/assets/11699283/7027789/e0c15340-dd51-11e4-9aea-135093d4f2e8.PNG)

With selecting PCM as out all is fine:

![mrswatson_pcm](https://cloud.githubusercontent.com/assets/11699283/7027978/26767662-dd53-11e4-9eac-452a7956b38b.PNG)

Would be nice if you can change the output of those messages to verbose mode only also for WAV output.
